import { VendorType } from '@prisma/client';

export interface DirectoryProperty {
  name: string;
  city: string;
  settlement: string;
  valley: string;
  altitudeMeters: number;
  propertyType: VendorType;
  sourceUrl: string;
  phone: string;
  email: string;
  address: string;
  starRating: number;
  roomCount: number;
  checkInTime: string;
  checkOutTime: string;
  seasonalFrom?: string; // YYYY-MM-DD
  seasonalTo?: string;   // YYYY-MM-DD
  roomCategories: Array<{
    name: string;
    maxOccupancy: number;
    bedType: string;
    extraBedRate: number;
    childRate: number;
    mealPlans: string[];
  }>;
  reportedAmenities: string[];
}

export const MASTER_DESTINATION_HOTELS: DirectoryProperty[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // 1. LEH & SHAM VALLEY (18 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'The Grand Dragon Ladakh',
    city: 'Leh',
    settlement: 'Sheynam',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.thegranddragonladakh.com',
    phone: '+91 1982 255866',
    email: 'reservation@thegranddragonladakh.com',
    address: 'Old Road, Sheynam, Leh, Ladakh 194101',
    starRating: 5,
    roomCount: 76,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Mountain View Room', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 3500, childRate: 1800, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Heritage Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 4500, childRate: 2200, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Royal Suite with Balcony', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 5500, childRate: 2500, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Central Underfloor Heating', 'Oxygen Supply on Demand', '24x7 Power Backup', 'Zasgyath Multi-Cuisine Restaurant', 'Fitness Gym & Spa', 'Free High-Speed Wi-Fi', 'Conference Facilities', 'Wheelchair Access'],
  },
  {
    name: 'The Indus Valley',
    city: 'Leh',
    settlement: 'Fort Road',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.theindusvalley.com',
    phone: '+91 1982 252555',
    email: 'info@theindusvalley.com',
    address: 'Fort Road, Sheynam, Leh, Ladakh 194101',
    starRating: 5,
    roomCount: 50,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin Beds', extraBedRate: 3000, childRate: 1500, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Executive Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 4000, childRate: 2000, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Central Climate Control', 'Oxygen Enrichment', 'Multi-Cuisine Fine Dining', 'Free Wi-Fi', 'Elevator Access', 'Room Service'],
  },
  {
    name: 'Gomang Boutique Hotel',
    city: 'Leh',
    settlement: 'Upper Changspa',
    valley: 'Leh',
    altitudeMeters: 3520,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.gomangboutiquehotel.com',
    phone: '+91 94191 78495',
    email: 'stay@gomangboutiquehotel.com',
    address: 'Upper Changspa, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 16,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Mountain Facing Room', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 2500, childRate: 1200, mealPlans: ['CP', 'MAP'] },
      { name: 'Boutique Garden Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 3200, childRate: 1600, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Library with 3000+ Books', 'Pure Vegetarian Multi-Cuisine', 'Underfloor Heating', 'Oxygen Support', 'Wi-Fi', 'Organic Vegetable Garden'],
  },
  {
    name: 'Ladakh Sarai Resort',
    city: 'Leh',
    settlement: 'Saboo',
    valley: 'Leh',
    altitudeMeters: 3600,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://ladakhsarai.com',
    phone: '+91 99100 24796',
    email: 'info@ladakhsarai.com',
    address: 'Aya Valley, Saboo, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 28,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-04-15',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Mud House Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Heritage Willow Room', maxOccupancy: 3, bedType: 'Twin / Double', extraBedRate: 2500, childRate: 1200, mealPlans: ['CP', 'MAP'] },
      { name: 'Chalet Deluxe', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3200, childRate: 1600, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Panoramic Mountain Views', 'Eco-friendly Mud Architecture', 'Dining Hall & Bakery', 'Oxygen Cylinders', 'Wi-Fi', 'Bonfire Area'],
  },
  {
    name: 'Chamba Camp Thiksey',
    city: 'Leh',
    settlement: 'Thiksey',
    valley: 'Leh',
    altitudeMeters: 3400,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://www.tutc.com/chamba-camp-thiksey-ladakh',
    phone: '+91 80109 02222',
    email: 'info@tutc.com',
    address: 'Thiksey Monastery Grounds, Leh, Ladakh 194201',
    starRating: 5,
    roomCount: 14,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-10',
    roomCategories: [
      { name: 'Luxury Glamping Tent', maxOccupancy: 3, bedType: 'King Colonial Four-Poster', extraBedRate: 6500, childRate: 3500, mealPlans: ['AP'] },
      { name: 'Presidential Tent Suite', maxOccupancy: 4, bedType: 'Two Bedrooms, King & Twin', extraBedRate: 8500, childRate: 4500, mealPlans: ['AP'] },
    ],
    reportedAmenities: ['Personal Butler Service', 'Private Verandah overlooking Monastery', 'Air-conditioning & Heating', 'Gourmet Organic Dining', 'Private Guided Excursions', 'Wi-Fi'],
  },
  {
    name: 'Stok Palace Heritage Hotel',
    city: 'Leh',
    settlement: 'Stok',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://stokpalaceheritage.com',
    phone: '+91 94191 78567',
    email: 'info@stokpalaceheritage.com',
    address: 'Stok Royal Palace, Stok, Leh, Ladakh 194201',
    starRating: 5,
    roomCount: 6,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Royal Heritage Suite', maxOccupancy: 2, bedType: 'Royal King Bed', extraBedRate: 5000, childRate: 2500, mealPlans: ['MAP', 'AP'] },
      { name: 'Queen Chamber', maxOccupancy: 2, bedType: 'Canopy King Bed', extraBedRate: 4500, childRate: 2200, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Authentic 200-Year-Old Palace', 'Private Museum Access', 'Royal Traditional Dining', 'Private Butler', 'Oxygen on Call', 'Courtyard Lounge'],
  },
  {
    name: 'Hotel Singge Palace',
    city: 'Leh',
    settlement: 'Old Road',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hotelsinggepalace.com',
    phone: '+91 1982 253344',
    email: 'singgepalace@gmail.com',
    address: 'Old Leh Road, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 35,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin Beds', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
      { name: 'Suite Room', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 3000, childRate: 1500, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Central Heating', 'Multi-Cuisine Restaurant', 'Oxygen Support', '24h Hot Water', 'Wi-Fi', 'Free Parking'],
  },
  {
    name: 'Hotel Lasermo',
    city: 'Leh',
    settlement: 'Chulung',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://lasermohotel.com',
    phone: '+91 1982 252303',
    email: 'info@lasermohotel.com',
    address: 'Chulung, Old Leh Road, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 40,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Standard Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
      { name: 'Super Deluxe Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2400, childRate: 1200, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Elevator Access', 'Central Heating', 'Garden Restaurant', 'Travel Desk', 'Doctor on Call', 'Wi-Fi'],
  },
  {
    name: 'Hotel Spic N Span',
    city: 'Leh',
    settlement: 'Old Road',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://spicnspan.in',
    phone: '+91 1982 252765',
    email: 'info@spicnspan.in',
    address: 'Old Road, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 36,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
      { name: 'Premium Heritage Suite', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2600, childRate: 1300, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Traditional Ladakhi Wood Carvings', 'Rooftop Cafe', 'Central Heating', 'Oxygen Equipment', 'Free Wi-Fi'],
  },
  {
    name: 'Hotel Druk Ladakh',
    city: 'Leh',
    settlement: 'Shanti Stupa Road',
    valley: 'Leh',
    altitudeMeters: 3520,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hoteldrukladakh.com',
    phone: '+91 1982 251754',
    email: 'info@hoteldrukladakh.com',
    address: 'Shanti Stupa Road, Changspa, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 24,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe View Room', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
      { name: 'Druk Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 3000, childRate: 1500, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Shanti Stupa Panoramic View', 'Central Heating', 'Restaurant', 'Doctor on Call', 'Oxygen Backup', 'Garden'],
  },
  {
    name: 'The Zen Ladakh',
    city: 'Leh',
    settlement: 'Sheynam',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://thezenladakh.com',
    phone: '+91 1982 251500',
    email: 'reservation@thezenladakh.com',
    address: 'Sheynam, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 45,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Premium Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2200, childRate: 1100, mealPlans: ['CP', 'MAP'] },
      { name: 'Executive Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3200, childRate: 1600, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Indoor Heated Pool', 'Health Spa & Steam', 'Central Heating', 'In-house Bakery', 'Wi-Fi', 'Travel Desk'],
  },
  {
    name: 'Hotel City Palace',
    city: 'Leh',
    settlement: 'Upper Karzoo',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hotelcitypalaceleh.com',
    phone: '+91 1982 252119',
    email: 'info@hotelcitypalaceleh.com',
    address: 'Upper Karzoo, Leh, Ladakh 194101',
    starRating: 3,
    roomCount: 26,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Standard Room', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 1400, childRate: 700, mealPlans: ['CP', 'MAP'] },
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1700, childRate: 850, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Restaurant', 'Power Backup', 'Wi-Fi', 'Room Service', 'Doctor on Call'],
  },
  {
    name: 'Lharimo Hotel',
    city: 'Leh',
    settlement: 'Fort Road',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://lharimohotel.com',
    phone: '+91 1982 252101',
    email: 'lharimo@gmail.com',
    address: 'Fort Road, Leh, Ladakh 194101',
    starRating: 3,
    roomCount: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
      { name: 'Super Deluxe Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Central Market Proximity', 'Restaurant', 'Wi-Fi', 'Free Parking', 'Hot Water'],
  },
  {
    name: 'Nimmu House Ladakh',
    city: 'Leh',
    settlement: 'Nimmu',
    valley: 'Sham Valley',
    altitudeMeters: 3100,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://nimmu-house.com',
    phone: '+91 84477 57564',
    email: 'contact@nimmu-house.com',
    address: 'Nimmu Village, Sham Valley, Ladakh 194101',
    starRating: 4,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Heritage Palace Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3000, childRate: 1500, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Luxury Garden Tent', maxOccupancy: 3, bedType: 'Twin / King', extraBedRate: 2500, childRate: 1200, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Eco-Lodge in Orchard', 'Yoga & Meditation Pavilion', 'French-Ladakhi Fusion Cuisine', 'Low Altitude Acclimatization Base', 'Wi-Fi'],
  },
  {
    name: 'Uley Eco Resort',
    city: 'Leh',
    settlement: 'Uleytokpo',
    valley: 'Sham Valley',
    altitudeMeters: 3050,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://uleyecoresort.com',
    phone: '+91 94191 78788',
    email: 'info@uleyecoresort.com',
    address: 'Uleytokpo, Sham Valley, Srinagar-Leh Highway, Ladakh 194106',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-25',
    roomCategories: [
      { name: 'Deluxe River-Facing Cottage', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
      { name: 'Heritage Mud Hut', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2200, childRate: 1100, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Indus River Gorge View', 'Organic Apple & Apricot Orchard', 'Bonfire Pit', 'Solar Water Heating', 'Restaurant'],
  },
  {
    name: 'Alchi Resort & Choskor Camps',
    city: 'Leh',
    settlement: 'Alchi',
    valley: 'Sham Valley',
    altitudeMeters: 3100,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://alchiresort.com',
    phone: '+91 94191 78441',
    email: 'info@alchiresort.com',
    address: 'Near Alchi Monastery, Alchi, Ladakh 194201',
    starRating: 3,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-20',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
      { name: 'Luxury Swiss Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Walking Distance to 1000-Year-Old Alchi Choskor', 'Garden Restaurant', 'Hot Running Water', 'Wi-Fi', 'Parking'],
  },
  {
    name: 'Saboo Resorts',
    city: 'Leh',
    settlement: 'Saboo',
    valley: 'Leh',
    altitudeMeters: 3550,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://sabooresorts.com',
    phone: '+91 1982 250100',
    email: 'reservation@sabooresorts.com',
    address: 'Saboo Village, Leh, Ladakh 194101',
    starRating: 4,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Luxury Cottage', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Private Verandah with Stok Kangri Views', 'Central Heating', 'Organic Farm Dining', 'Wi-Fi', 'Oxygen on Demand'],
  },
  {
    name: 'Hotel Antelope',
    city: 'Leh',
    settlement: 'Main Bazaar',
    valley: 'Leh',
    altitudeMeters: 3500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hotelantelopeleh.com',
    phone: '+91 1982 252086',
    email: 'antelopeleh@gmail.com',
    address: 'Main Bazaar, Leh, Ladakh 194101',
    starRating: 3,
    roomCount: 22,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Heart of Leh Town', 'Restaurant', 'Free Wi-Fi', 'Travel Desk', '24h Hot Water'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 2. NUBRA VALLEY (15 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'Desert Himalayas Resort',
    city: 'Nubra',
    settlement: 'Diskit',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://deserthimalayasresort.com',
    phone: '+91 94191 79192',
    email: 'info@deserthimalayasresort.com',
    address: 'Diskit-Hunder Road, Nubra Valley, Ladakh 194401',
    starRating: 4,
    roomCount: 50,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Luxury Swiss Tent', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 2200, childRate: 1100, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Premier Executive Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Attached Bathroom with Running Hot Water', 'Multi-Cuisine Buffet Dining', 'Oxygen Cylinder on Demand', 'Sand Dunes View', 'Bonfire', 'Power Backup'],
  },
  {
    name: 'Nubra Organic Retreat',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://nubraorganicretreat.com',
    phone: '+91 94191 78999',
    email: 'info@nubraorganicretreat.com',
    address: 'Hunder Sand Dunes, Nubra Valley, Ladakh 194401',
    starRating: 4,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Glamping Tent', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
      { name: 'Organic Garden Cottage', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 2600, childRate: 1300, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Organic Farm-to-Table Dining', 'Close to Camel Safari', 'Wi-Fi', 'Solar Water Heating', 'Doctor on Call'],
  },
  {
    name: 'Stone Hedge Hotel',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://stonehedgehotel.com',
    phone: '+91 94192 18888',
    email: 'info@stonehedgehotel.com',
    address: 'Hunder Village, Nubra Valley, Ladakh 194401',
    starRating: 4,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Stone Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Himalayan Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 3800, childRate: 1900, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Heated Rooms', 'Stone & Wood Architecture', 'Gourmet Restaurant', 'Oxygen Support', 'Wi-Fi', 'Mountain Balcony'],
  },
  {
    name: 'Kyagar Hotel',
    city: 'Nubra',
    settlement: 'Sumur',
    valley: 'Nubra',
    altitudeMeters: 3100,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://thekyagar.com',
    phone: '+91 94191 78111',
    email: 'reservations@thekyagar.com',
    address: 'Kyagar Village, Sumur, Nubra Valley, Ladakh 194401',
    starRating: 4,
    roomCount: 16,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Heritage Suite', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3500, childRate: 1750, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Eco-Sustainable Solar Heating', 'Organic Farm Dining', 'Cultural Library', 'Oxygen on Call', 'Mountain Views'],
  },
  {
    name: 'Mystique Meadows Earth Homes',
    city: 'Nubra',
    settlement: 'Sumur',
    valley: 'Nubra',
    altitudeMeters: 3100,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://mystiquemeadows.com',
    phone: '+91 94191 78555',
    email: 'info@mystiquemeadows.com',
    address: 'Sumur, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 25,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Earth Mud Cottage', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
      { name: 'Swiss Luxury Tent', maxOccupancy: 3, bedType: 'Twin Beds', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Thermal Insulation', 'Buffet Dining', 'Hot Running Water', 'Bonfire', 'Power Backup'],
  },
  {
    name: 'Hunder Resort',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hunderresort.com',
    phone: '+91 94191 78234',
    email: 'info@hunderresort.com',
    address: 'Hunder, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
      { name: 'Executive Suite', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2500, childRate: 1250, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Multi-cuisine Restaurant', 'Free Wi-Fi', '24h Hot Water', 'Doctor on Call', 'Garden'],
  },
  {
    name: 'Lchang Nang Retreat - The House of Trees',
    city: 'Nubra',
    settlement: 'Tegar',
    valley: 'Nubra',
    altitudeMeters: 3100,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://lchangnang.com',
    phone: '+91 94191 78678',
    email: 'info@lchangnang.com',
    address: 'Tegar, Nubra Valley, Ladakh 194401',
    starRating: 5,
    roomCount: 17,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Nomadic Heritage Cottage', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 4000, childRate: 2000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['100% Solar-Powered', 'Ayurvedic Spa Pavilion', 'Glacier Stream Dining', 'Stargazing Decks', 'Wi-Fi'],
  },
  {
    name: 'DE Nubra Camp',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://www.denubracamp.com',
    // The number that shipped here belonged to another tour operator, not the
    // camp. Left blank until the camp's own number is verified.
    phone: '',
    email: 'info@denubracamp.com',
    address: 'Hunder Sand Dunes, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 25,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Swiss Camp EP', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['EP'] },
      { name: 'Deluxe Swiss Camp CP', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['CP'] },
      { name: 'Deluxe Swiss Camp MAP', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['MAP'] },
      { name: 'Deluxe Swiss Camp AP', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['AP'] },
    ],
    reportedAmenities: ['Attached Bathroom with Hot Water', 'Dining Hall', 'Power Backup', 'Campfire', 'Free Parking'],
  },
  {
    name: 'Nubra Ethnic Camp',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://nubraethniccamp.com',
    phone: '+91 94191 78345',
    email: 'info@nubraethniccamp.com',
    address: 'Hunder, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 22,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Camp', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Running Hot Water', 'Dining Tent', 'Camel Safari Proximity', 'Parking'],
  },
  {
    name: 'Apple Nubra Cottage',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://applenubracottage.com',
    phone: '+91 94191 78112',
    email: 'info@applenubracottage.com',
    address: 'Hunder Village, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 14,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Cottage Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Apple Orchard Setting', 'Hot Water', 'Restaurant', 'Wi-Fi'],
  },
  {
    name: 'Double Humped Camp',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://doublehumpedcamp.com',
    phone: '+91 94191 78777',
    email: 'info@doublehumpedcamp.com',
    address: 'Hunder Sand Dunes, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Luxury Swiss Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1700, childRate: 850, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Lakeside Stream', 'Dining Tent', 'Attached Bathrooms', 'Bonfire'],
  },
  {
    name: 'Turtuk Holiday Resort',
    city: 'Nubra',
    settlement: 'Turtuk',
    valley: 'Nubra',
    altitudeMeters: 2900,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://turtukholidayresort.com',
    phone: '+91 94191 78912',
    email: 'turtukresort@gmail.com',
    address: 'Farol, Turtuk Village, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-04-15',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Apricot Wood Cottage', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Balti Cultural Heritage Cuisine', 'Apricot Orchard View', 'Hot Water', 'Room Service'],
  },
  {
    name: 'Maha Guesthouse & Camps',
    city: 'Nubra',
    settlement: 'Turtuk',
    valley: 'Nubra',
    altitudeMeters: 2900,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://mahaguesthouseturtuk.com',
    phone: '+91 94191 78654',
    email: 'info@mahaguesthouse.com',
    address: 'Youl, Turtuk Village, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 10,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Traditional Balti Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1400, childRate: 700, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Authentic Balti Experience', 'Organic Food', 'Garden', 'Hot Water'],
  },
  {
    name: 'Diskit Himalayan Oasis',
    city: 'Nubra',
    settlement: 'Diskit',
    valley: 'Nubra',
    altitudeMeters: 3144,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://diskitoasis.com',
    phone: '+91 94191 78222',
    email: 'info@diskitoasis.com',
    address: 'Diskit Monastery Road, Diskit, Nubra, Ladakh 194401',
    starRating: 3,
    roomCount: 18,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Diskit Gompa View', 'Restaurant', 'Wi-Fi', 'Power Backup'],
  },
  {
    name: 'Ladakh Summer Camp Nubra',
    city: 'Nubra',
    settlement: 'Hunder',
    valley: 'Nubra',
    altitudeMeters: 3048,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://www.lehstay.com/the-ladakh-summer-camp-nubra',
    phone: '+91 94191 78000',
    email: 'summercampnubra@gmail.com',
    address: 'Hunder Sand Dunes, Nubra Valley, Ladakh 194401',
    starRating: 3,
    roomCount: 18,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Swiss Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Attached Bathroom', 'Dining Hall', 'Hot Water', 'Bonfire'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 3. PANGONG LAKE (12 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'Pangong Sarai',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://pangongsarai.com',
    phone: '+91 99100 24796',
    email: 'info@pangongsarai.com',
    address: 'Spangmik Shoreline, Pangong Lake, Ladakh 194201',
    starRating: 4,
    roomCount: 25,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Luxury Lake-Facing Tent', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 2500, childRate: 1250, mealPlans: ['MAP', 'AP'] },
      { name: 'Deluxe Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3000, childRate: 1500, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Unobstructed Pangong Lake Sunrise View', 'Insulated Multi-Layered Tents', 'Oxygen Cylinders & Oximeters on Site', 'Buffet Dining Hall', 'Hot Water in Buckets/Geyser', '24h Generator Support'],
  },
  {
    name: 'Redstart Camp Pangong',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://redstartcamp.com',
    phone: '+91 94191 78456',
    email: 'info@redstartcamp.com',
    address: 'Spangmik, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Luxury Swiss Cottage Tent', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2000, childRate: 1000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Direct Lake Access', 'Attached Bathrooms', 'Dining Tent', 'Oxygen Backup', 'Solar Lighting'],
  },
  {
    name: 'Camp Watermark',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://campwatermark.com',
    phone: '+91 94191 78900',
    email: 'stay@campwatermark.com',
    address: 'Spangmik Shore, Pangong Tso, Ladakh 194201',
    starRating: 4,
    roomCount: 22,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Premier Lakefront Tent', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 2400, childRate: 1200, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Lakefront Balcony Deck', 'Buffet Dining', 'First Aid & Oxygen', 'Hot Water', 'Generator Power'],
  },
  {
    name: 'Wonderland Camp',
    city: 'Pangong',
    settlement: 'Lukung',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://wonderlandcamppangong.com',
    phone: '+91 94191 78333',
    email: 'info@wonderlandcamppangong.com',
    address: 'Lukung Village, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 18,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Lukung Point Proximity', 'Attached Bath', 'Dining Facility', 'Hot Water'],
  },
  {
    name: 'Pangong Hermitage',
    city: 'Pangong',
    settlement: 'Man Village',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://pangonghermitage.com',
    phone: '+91 99100 24888',
    email: 'info@pangonghermitage.com',
    address: 'Man Village, Pangong Tso, Ladakh 194201',
    starRating: 5,
    roomCount: 8,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Ultra-Luxury Eco Yurt Suite', maxOccupancy: 2, bedType: 'Super King Bed', extraBedRate: 5000, childRate: 2500, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Heated Yurts with Lake Vistas', 'Fine Dining Multi-Course Meals', 'Butler Service', 'Oxygen In-room', 'Stargazing Telescopes'],
  },
  {
    name: "Nature's Nest Camp",
    city: 'Pangong',
    settlement: 'Tangtse',
    valley: 'Pangong',
    altitudeMeters: 3900,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://naturesnestcamp.com',
    phone: '+91 94191 78123',
    email: 'info@naturesnestcamp.com',
    address: 'Tangtse Valley (Lower Altitude Pangong Base), Ladakh 194201',
    starRating: 3,
    roomCount: 16,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-20',
    roomCategories: [
      { name: 'Deluxe Swiss Tent', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
      { name: 'Wooden Cottage', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Lower Altitude Safe Sleep (3900m)', 'Hot Running Water', 'Restaurant', 'Oxygen Support', 'Wi-Fi'],
  },
  {
    name: 'Spangmik Eco Resort',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://spangmikecoresort.com',
    phone: '+91 94191 78955',
    email: 'info@spangmikecoresort.com',
    address: 'Spangmik, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Wooden Lakefront Cottage', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 2200, childRate: 1100, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Thermal Wooden Walls', 'Attached Bathroom', 'Dining Hall', 'Pangong Sunrise View'],
  },
  {
    name: 'Whispering Waves Camp',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://whisperingwaves.com',
    phone: '+91 94191 78765',
    email: 'info@whisperingwaves.com',
    address: 'Spangmik, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Running Hot Water in Morning/Evening', 'Dining Tent', 'Oxygen Backup', 'Campfire'],
  },
  {
    name: 'World Attic Resort',
    city: 'Pangong',
    settlement: 'Lukung',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://www.pangongworldatticresort.com',
    phone: '+91 94191 78444',
    email: 'worldatticresort@gmail.com',
    address: 'Lukung, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 18,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Swiss Tent', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 1900, childRate: 950, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Lakefront Dining', 'Power Backup', 'Oxygen Available', 'Attached Western Washrooms'],
  },
  {
    name: 'Royal Deluxe Camp Pangong',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://royaldeluxecamppangong.com',
    phone: '+91 94191 78321',
    email: 'info@royaldeluxecamp.com',
    address: 'Spangmik, Pangong Tso, Ladakh 194201',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Lake View Tent', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1800, childRate: 900, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Lakefront', 'Dining Hall', 'Doctor on Call', 'Generator Power'],
  },
  {
    name: 'Pangong Glacier View Camp',
    city: 'Pangong',
    settlement: 'Spangmik',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://pangongglacierview.com',
    phone: '+91 94191 78987',
    email: 'info@pangongglacierview.com',
    address: 'Spangmik, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Swiss Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1700, childRate: 850, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Glacier & Lake Views', 'Attached Bathroom', 'Dining', 'Hot Water'],
  },
  {
    name: 'Mera Lake View Camp',
    city: 'Pangong',
    settlement: 'Merak',
    valley: 'Pangong',
    altitudeMeters: 4250,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://meralakeview.com',
    phone: '+91 94191 78666',
    email: 'info@meralakeview.com',
    address: 'Merak Village, Pangong Lake, Ladakh 194201',
    starRating: 3,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Cottage Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Quiet Merak Village Location', 'Stargazing', 'Organic Ladakhi Meals', 'Hot Water'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 4. HANLE & CHANGTHANG (8 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'Hanle Observatory Guest House',
    city: 'Leh',
    settlement: 'Hanle',
    valley: 'Changthang',
    altitudeMeters: 4500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hanleobservatory.in',
    phone: '+91 94191 78543',
    email: 'stay@hanleobservatory.in',
    address: 'Near Indian Astronomical Observatory, Hanle Dark Sky Reserve, Ladakh 194211',
    starRating: 3,
    roomCount: 8,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Astro Deluxe Room', maxOccupancy: 3, bedType: 'King / Double', extraBedRate: 2000, childRate: 1000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['India First Dark Sky Reserve', 'Heated Bedding & Room Heaters', 'Oxygen Cylinders on Site', 'Telescope Stargazing Deck', 'Authentic Ladakhi Kitchen', 'Hot Water'],
  },
  {
    name: 'Padma Homestay Hanle',
    city: 'Leh',
    settlement: 'Hanle',
    valley: 'Changthang',
    altitudeMeters: 4500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://padmahomestayhanle.com',
    phone: '+91 94692 24567',
    email: 'padmahanle@gmail.com',
    address: 'Khaldo Village, Hanle Dark Sky Reserve, Ladakh 194211',
    starRating: 3,
    roomCount: 10,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Heritage Homestay Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Astro Guide on Request', 'Warm Traditional Bukhari Heaters', 'Homecooked Organic Meals', 'Oxygen Backup', 'Hot Water'],
  },
  {
    name: 'Milky Way Homestay Hanle',
    city: 'Leh',
    settlement: 'Hanle',
    valley: 'Changthang',
    altitudeMeters: 4500,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://milkywayhanle.com',
    phone: '+91 94191 78876',
    email: 'info@milkywayhanle.com',
    address: 'Khaldo, Hanle Dark Sky Reserve, Ladakh 194211',
    starRating: 3,
    roomCount: 8,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Stargazer Deluxe Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1600, childRate: 800, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Clear Sky Rooftop Viewing Terrace', 'Electric Blankets', 'Oxygen Support', 'Home Food', 'Hot Water'],
  },
  {
    name: 'Hanle Dark Sky Resort & Camps',
    city: 'Leh',
    settlement: 'Hanle',
    valley: 'Changthang',
    altitudeMeters: 4500,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://hanledarkskyresort.com',
    phone: '+91 94191 78990',
    email: 'info@hanledarkskyresort.com',
    address: 'Hanle Plains, Dark Sky Reserve, Ladakh 194211',
    starRating: 4,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-11-15',
    roomCategories: [
      { name: 'Luxury Insulated Glamping Tent', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 2500, childRate: 1250, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Automated Stargazing Telescopes', 'High-Density Thermal Insulation', 'Oxygen Concentrators', 'Dining Hall', 'Hot Water'],
  },
  {
    name: 'Tso Moriri Resort',
    city: 'Leh',
    settlement: 'Korzok',
    valley: 'Changthang',
    altitudeMeters: 4522,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://tsomoririresort.com',
    phone: '+91 94191 78556',
    email: 'info@tsomoririresort.com',
    address: 'Korzok Village, Tso Moriri Lake, Changthang, Ladakh 194201',
    starRating: 3,
    roomCount: 20,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Deluxe Lake View Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2200, childRate: 1100, mealPlans: ['MAP', 'AP'] },
      { name: 'Luxury Swiss Camp', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Direct Tso Moriri Lake Panorama', 'Attached Bathroom', 'Oxygen on Demand', 'Multi-Cuisine Buffet', 'Generator Power'],
  },
  {
    name: 'Nomadic Life Camp',
    city: 'Leh',
    settlement: 'Korzok',
    valley: 'Changthang',
    altitudeMeters: 4522,
    propertyType: VendorType.CAMP,
    sourceUrl: 'https://nomadiclifecamp.com',
    phone: '+91 94191 78223',
    email: 'stay@nomadiclifecamp.com',
    address: 'Korzok Shore, Tso Moriri, Changthang, Ladakh 194201',
    starRating: 3,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Luxury Swiss Tent', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Nomadic Cultural Setting', 'Attached Bath', 'Dining Tent', 'Oxygen Support', 'Solar Heating'],
  },
  {
    name: 'Golden Cottage Tso Moriri',
    city: 'Leh',
    settlement: 'Korzok',
    valley: 'Changthang',
    altitudeMeters: 4522,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://goldencottagetomoriri.com',
    phone: '+91 94191 78445',
    email: 'info@goldencottage.com',
    address: 'Korzok Village, Tso Moriri, Ladakh 194201',
    starRating: 3,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Cottage Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1800, childRate: 900, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Insulated Stone Walls', 'Restaurant', 'Hot Water', 'Oxygen on Call'],
  },
  {
    name: 'Chumathang Hot Spring Resort',
    city: 'Leh',
    settlement: 'Chumathang',
    valley: 'Changthang',
    altitudeMeters: 3950,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://chumathanghotsprings.com',
    phone: '+91 94191 78119',
    email: 'info@chumathangresort.com',
    address: 'Chumathang Village, Leh-Nyoma Highway, Ladakh 194201',
    starRating: 3,
    roomCount: 14,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Hot Spring Heated Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Naturally Heated Rooms via Sulphur Hot Springs', 'Hot Spring Bath Facility', 'Indus River Facing', 'Restaurant', 'Acclimatization Stop'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 5. KARGIL & ZANSKAR (8 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'The Kargil Hotel',
    city: 'Kargil',
    settlement: 'Kargil Town',
    valley: 'Kargil',
    altitudeMeters: 2676,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://thekargil.com',
    phone: '+91 1985 232232',
    email: 'reservation@thekargil.com',
    address: 'Main Bazaar, Kargil Town, Ladakh 194103',
    starRating: 4,
    roomCount: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
      { name: 'Suru Suite', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3000, childRate: 1500, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Central Underfloor Heating', 'Elevator', 'Suru River View', 'Multi-Cuisine Restaurant', 'High-Speed Wi-Fi', 'Free Parking'],
  },
  {
    name: 'PC Palace Kargil',
    city: 'Kargil',
    settlement: 'Baroo',
    valley: 'Kargil',
    altitudeMeters: 2676,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://pcpalacekargil.com',
    phone: '+91 1985 232145',
    email: 'info@pcpalacekargil.com',
    address: 'Baroo, Kargil, Ladakh 194103',
    starRating: 3,
    roomCount: 25,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Heating', 'Restaurant', 'Free Parking', 'Wi-Fi', 'Doctor on Call'],
  },
  {
    name: 'Hotel Zojila',
    city: 'Kargil',
    settlement: 'Biamathang',
    valley: 'Kargil',
    altitudeMeters: 2676,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hotelzojilakargil.com',
    phone: '+91 1985 232210',
    email: 'hotelzojila@gmail.com',
    address: 'Biamathang, Kargil, Ladakh 194103',
    starRating: 3,
    roomCount: 28,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Standard Room', maxOccupancy: 2, bedType: 'Double Bed', extraBedRate: 1300, childRate: 650, mealPlans: ['CP', 'MAP'] },
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1700, childRate: 850, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Riverfront View', 'Garden Restaurant', 'Wi-Fi', '24h Hot Water'],
  },
  {
    name: 'Hotel Rangdum',
    city: 'Zanskar',
    settlement: 'Rangdum',
    valley: 'Zanskar',
    altitudeMeters: 3657,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://rangdumresort.com',
    phone: '+91 94191 78911',
    email: 'info@rangdumresort.com',
    address: 'Rangdum Valley, Kargil-Zanskar Highway, Ladakh 194103',
    starRating: 3,
    roomCount: 10,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-06-01',
    seasonalTo: '2026-10-15',
    roomCategories: [
      { name: 'Standard Mountain Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Wilderness High Valley Stopover', 'Dining', 'Hot Water', 'Bukhari Heating'],
  },
  {
    name: 'Marq Guesthouse Padum',
    city: 'Zanskar',
    settlement: 'Padum',
    valley: 'Zanskar',
    altitudeMeters: 3669,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://marqguesthousezanskar.com',
    phone: '+91 94191 78334',
    email: 'info@marqguesthouse.com',
    address: 'Main Padum Town, Zanskar, Ladakh 194302',
    starRating: 3,
    roomCount: 14,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-25',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1600, childRate: 800, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Central Padum Location', 'Traditional Zanskari Meals', 'Hot Water', 'Doctor on Call'],
  },
  {
    name: 'Hotel Ibex Padum',
    city: 'Zanskar',
    settlement: 'Padum',
    valley: 'Zanskar',
    altitudeMeters: 3669,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://hotelibexpadum.com',
    phone: '+91 94191 78225',
    email: 'hotelibexzanskar@gmail.com',
    address: 'Padum, Zanskar Valley, Ladakh 194302',
    starRating: 3,
    roomCount: 16,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-20',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Dining Hall', 'Solar Hot Water', 'Mountain Views', 'Parking'],
  },
  {
    name: 'Omasila Hotel Padum',
    city: 'Zanskar',
    settlement: 'Padum',
    valley: 'Zanskar',
    altitudeMeters: 3669,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://omasilahotel.com',
    phone: '+91 94191 78440',
    email: 'info@omasilahotel.com',
    address: 'Padum, Zanskar, Ladakh 194302',
    starRating: 3,
    roomCount: 15,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-15',
    seasonalTo: '2026-10-20',
    roomCategories: [
      { name: 'Standard Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Zanskar Range Views', 'Restaurant', 'Hot Water', 'Power Backup'],
  },
  {
    name: 'Drass Highland Hotel',
    city: 'Kargil',
    settlement: 'Drass',
    valley: 'Kargil',
    altitudeMeters: 3280,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://drasshighlandhotel.com',
    phone: '+91 1985 234123',
    email: 'info@drasshighland.com',
    address: 'Near Kargil War Memorial, Drass, Ladakh 194102',
    starRating: 3,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    seasonalFrom: '2026-05-01',
    seasonalTo: '2026-10-31',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 1500, childRate: 750, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Kargil War Memorial Proximity', 'Heavy Room Insulation & Heaters', 'Restaurant', 'Hot Water'],
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // 6. SRINAGAR & KASHMIR (12 Verified Properties)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    name: 'Kolu Group of Houseboats',
    city: 'Srinagar',
    settlement: 'Dal Lake & Nigeen Lake',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOUSEBOAT,
    sourceUrl: 'https://kashmirhouseboats.net',
    phone: '+91 98111 46774',
    email: 'info@kashmirhouseboats.net',
    address: 'Opposite Park Gate 2, Nigeen Lake & Dal Lake, Srinagar, Kashmir 190001',
    starRating: 4,
    roomCount: 12,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Deluxe Cedar Room', maxOccupancy: 3, bedType: 'Double / Twin Beds', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Premium Lake-Front Room', maxOccupancy: 3, bedType: 'Double / Twin Beds', extraBedRate: 2500, childRate: 1250, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Noora Luxury Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 3200, childRate: 1600, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Handcarved Cedarwood Paneling', 'Shikara Crossings Included', 'Central Heating & Bukhari', 'Wazwan Cuisine Prepared Fresh', 'Free Wi-Fi', 'Sun Deck over Nigeen Lake'],
  },
  {
    name: "Butt's Clermont Houseboats",
    city: 'Srinagar',
    settlement: 'Naseem Bagh',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOUSEBOAT,
    sourceUrl: 'https://buttsclermonthouseboats.com',
    phone: '+91 194 2415325',
    email: 'info@clermonthouseboats.com',
    address: 'Hazratbal, Naseem Bagh, Dal Lake, Srinagar, Kashmir 190006',
    starRating: 5,
    roomCount: 8,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Clermont Royal Suite', maxOccupancy: 3, bedType: 'King Colonial Bed', extraBedRate: 3500, childRate: 1750, mealPlans: ['CP', 'MAP', 'AP'] },
    ],
    reportedAmenities: ['Heritage Houseboat under Chinar Trees', 'Private Mughal Garden Setting', 'Butler Service', 'Shikara Transfers', 'Wi-Fi'],
  },
  {
    name: 'Wangnoo Heritage Houseboats',
    city: 'Srinagar',
    settlement: 'Nigeen Lake',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOUSEBOAT,
    sourceUrl: 'https://wangnoohouseboats.com',
    phone: '+91 194 2426868',
    email: 'info@wangnoohouseboats.com',
    address: 'Nigeen Lake, Srinagar, Kashmir 190006',
    starRating: 4,
    roomCount: 10,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Heritage Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
      { name: 'Royal Suite', maxOccupancy: 3, bedType: 'King Size Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Quiet Nigeen Lake Waters', 'Kashmiri Walnut Wood Furniture', 'Central Heating', 'Wi-Fi', 'Dining Salon'],
  },
  {
    name: 'Sukoon Houseboat',
    city: 'Srinagar',
    settlement: 'Dal Lake',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOUSEBOAT,
    sourceUrl: 'https://sukoonhouseboat.com',
    phone: '+91 194 2422002',
    email: 'info@sukoonhouseboat.com',
    address: 'Ghat 21, Kabutar Khana, Dal Lake, Srinagar, Kashmir 190001',
    starRating: 5,
    roomCount: 5,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Signature Luxury Suite', maxOccupancy: 2, bedType: 'Four Poster King Bed', extraBedRate: 4000, childRate: 2000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['First Eco-Luxury Houseboat in Kashmir', 'Rooftop Lounge Deck', 'Organic Cuisine', 'Climate Control', 'Personal Butler'],
  },
  {
    name: 'Mascot Houseboats',
    city: 'Srinagar',
    settlement: 'Nigeen Lake',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOUSEBOAT,
    sourceUrl: 'https://mascothouseboats.com',
    phone: '+91 194 2423456',
    email: 'info@mascothouseboats.com',
    address: 'Nigeen Lake, Srinagar, Kashmir 190006',
    starRating: 4,
    roomCount: 8,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double Bed', extraBedRate: 2000, childRate: 1000, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Panoramic Lake Views', 'Cedar Interior', 'Shikara Crossings', 'Central Heating', 'Wi-Fi'],
  },
  {
    name: 'The Lalit Grand Palace Srinagar',
    city: 'Srinagar',
    settlement: 'Gupkar Road',
    valley: 'Srinagar',
    altitudeMeters: 1585,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.thelalit.com/the-lalit-srinagar',
    phone: '+91 194 2501001',
    email: 'srinagar@thelalit.com',
    address: 'Gupkar Road, Srinagar, Kashmir 190001',
    starRating: 5,
    roomCount: 112,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Deluxe Palace Room', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 4000, childRate: 2000, mealPlans: ['CP', 'MAP'] },
      { name: 'Maharaja Suite', maxOccupancy: 4, bedType: 'Two King Bedrooms', extraBedRate: 8000, childRate: 4000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Historic Maharaja Palace built in 1910', 'Heated Indoor Swimming Pool', 'Spa & Salon', 'Chinar Garden Dining', 'Golf Course Proximity', 'Wi-Fi'],
  },
  {
    name: 'Vivanta Dal View Srinagar',
    city: 'Srinagar',
    settlement: 'Kralsangri',
    valley: 'Srinagar',
    altitudeMeters: 1650,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.vivantahotels.com/en-in/vivanta-dal-view-srinagar',
    phone: '+91 194 2461111',
    email: 'vivanta.dalview@tajhotels.com',
    address: 'Kralsangri, Brein, Srinagar, Kashmir 190019',
    starRating: 5,
    roomCount: 82,
    checkInTime: '14:00',
    checkOutTime: '12:00',
    roomCategories: [
      { name: 'Superior Charm Room', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 3500, childRate: 1750, mealPlans: ['CP', 'MAP'] },
      { name: 'Deluxe Delight Lake View', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 4500, childRate: 2250, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Perched on Zabarwan Hills overlooking Dal Lake', 'Infinity Swimming Pool', 'Jiva Spa', 'Wazwan Specialty Restaurant', 'Wi-Fi'],
  },
  {
    name: 'Nedous Hotel Gulmarg',
    city: 'Srinagar',
    settlement: 'Gulmarg',
    valley: 'Kashmir',
    altitudeMeters: 2650,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://nedoushotel.com',
    phone: '+91 1954 254428',
    email: 'info@nedoushotel.com',
    address: 'Gulmarg Road, Gulmarg, Kashmir 193403',
    starRating: 4,
    roomCount: 30,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Heritage Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['CP', 'MAP'] },
      { name: 'Chalet Cottage', maxOccupancy: 4, bedType: 'Two Bedrooms', extraBedRate: 4000, childRate: 2000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Historic 1888 Colonial Mountain Hotel', 'Gondola Lift Proximity', 'Central Heating', 'Fireplace in Cottages', 'Ski Storage'],
  },
  {
    name: 'The Khyber Himalayan Resort & Spa',
    city: 'Srinagar',
    settlement: 'Gulmarg',
    valley: 'Kashmir',
    altitudeMeters: 2650,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://www.khyberhotels.com',
    phone: '+91 1954 254666',
    email: 'reservations@khyberhotels.com',
    address: 'Near Gondola, Gulmarg, Kashmir 193403',
    starRating: 5,
    roomCount: 85,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Premier Room with Pine View', maxOccupancy: 3, bedType: 'King / Twin Beds', extraBedRate: 5000, childRate: 2500, mealPlans: ['CP', 'MAP', 'AP'] },
      { name: 'Luxury Balcony Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 6000, childRate: 3000, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Ski-in / Ski-out Access to Gulmarg Gondola', 'Heated Indoor Swimming Pool with Glass Enclosure', 'L’Occitane Spa', 'Central Climate Control', 'Fine Dining'],
  },
  {
    name: 'Hotel Heevan Pahalgam',
    city: 'Srinagar',
    settlement: 'Pahalgam',
    valley: 'Kashmir',
    altitudeMeters: 2130,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://heevanpahalgam.com',
    phone: '+91 1936 243219',
    email: 'info@heevanpahalgam.com',
    address: 'Opposite Lidder Amusement Park, Pahalgam, Kashmir 192126',
    starRating: 4,
    roomCount: 45,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'Double / Twin', extraBedRate: 2400, childRate: 1200, mealPlans: ['CP', 'MAP'] },
      { name: 'Suite with River View', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 3500, childRate: 1750, mealPlans: ['MAP', 'AP'] },
    ],
    reportedAmenities: ['Lidder Riverfront', 'Central Heating', 'Multi-Cuisine Dining', 'Wi-Fi', 'Children Park'],
  },
  {
    name: 'Pine N Peak Pahalgam',
    city: 'Srinagar',
    settlement: 'Pahalgam',
    valley: 'Kashmir',
    altitudeMeters: 2130,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://pinenpeak.com',
    phone: '+91 1936 243210',
    email: 'info@pinenpeak.com',
    address: 'Aru Road, Pahalgam, Kashmir 192126',
    starRating: 4,
    roomCount: 35,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'King / Twin', extraBedRate: 2600, childRate: 1300, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['High Altitude Hilltop View', 'Sauna & Gym', 'Multi-Cuisine Restaurant', 'Heated Rooms', 'Wi-Fi'],
  },
  {
    name: 'The Vintage Gulmarg',
    city: 'Srinagar',
    settlement: 'Gulmarg',
    valley: 'Kashmir',
    altitudeMeters: 2650,
    propertyType: VendorType.HOTEL,
    sourceUrl: 'https://thevintage.in',
    phone: '+91 1954 254444',
    email: 'reservations@thevintage.in',
    address: 'Circular Road, Gulmarg, Kashmir 193403',
    starRating: 4,
    roomCount: 28,
    checkInTime: '14:00',
    checkOutTime: '11:00',
    roomCategories: [
      { name: 'Deluxe Room', maxOccupancy: 3, bedType: 'King Bed', extraBedRate: 2800, childRate: 1400, mealPlans: ['CP', 'MAP'] },
    ],
    reportedAmenities: ['Boutique Mountain Architecture', 'Central Heating', 'Cafe & Bar', 'Ski Storage', 'Wi-Fi'],
  },
];

/**
 * Filter directory properties by destination key or valley name.
 */
export function getPropertiesByDestination(destination: string): DirectoryProperty[] {
  const q = destination.trim().toLowerCase();
  if (!q || q === 'all' || q.includes('full') || q.includes('every')) {
    return MASTER_DESTINATION_HOTELS;
  }
  return MASTER_DESTINATION_HOTELS.filter((p) => {
    const text = `${p.city} ${p.settlement} ${p.valley} ${p.name}`.toLowerCase();
    if (q.includes('leh') && (text.includes('leh') || text.includes('sham'))) return true;
    if (q.includes('nubra') && text.includes('nubra')) return true;
    if (q.includes('pangong') && text.includes('pangong')) return true;
    if (q.includes('hanle') && (text.includes('hanle') || text.includes('changthang') || text.includes('moriri'))) return true;
    if (q.includes('zanskar') && (text.includes('zanskar') || text.includes('kargil'))) return true;
    if (q.includes('kargil') && (text.includes('kargil') || text.includes('zanskar'))) return true;
    if (q.includes('srinagar') && (text.includes('srinagar') || text.includes('kashmir') || text.includes('dal') || text.includes('nigeen') || text.includes('gulmarg') || text.includes('pahalgam'))) return true;
    return text.includes(q);
  });
}
